export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
