export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'

export const GET_USERNAME_PASSWORD_SUCCESS = 'GET_USERNAME_PASSWORD_SUCCESS'
export const CURRENT_USERNAME = 'CURRENT_USERNAME'
export const CURRENT_PASSWORD = 'CURRENT_PASSWORD'
export const IS_ONLINE = false
